title: OG Knowledge Base
description: Open Docs for Open Data
url: https://patlittle.github.io
baseurl: /OG-Knowledge-Base
markdown: kramdown
permalink: pretty

collections:
  docs_en:
    output: true
    permalink: /en/docs/:path/
  docs_fr:
    output: true
    permalink: /fr/docs/:path/

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

defaults:
  - scope:
      path: ""
    values:
      layout: docs
  - scope:
      path: ""
      type: docs_en
    values:
      layout: docs_page
      lang: en
  - scope:
      path: ""
      type: docs_fr
    values:
      layout: docs_page
      lang: fr

exclude:
  - README.md
