title: OG Knowledge Base
description: Documentation site powered by Jekyll + GC Design System
theme: null
markdown: kramdown
permalink: pretty

collections:
  docs:
    output: true
    permalink: /docs/:path/

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

defaults:
  - scope:
      path: ""
    values:
      layout: docs
  - scope:
      path: ""
      type: docs
    values:
      layout: docs_page

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
